# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ data_string.website.title }}, {{  data_string.website.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Settings for the plugins in the _plugins folder.
plugin:
  imager:
    dir_posts:                  assets/images/posts
  # To see language support, go to the plugin "_plugins/reading_time.rb"
  reading_time:
    locale:                     en_US
  # To see language support, go to the plugin "_plugins/datelang.rb"
  datelang:
    locale:                     en_US
    reload:                     true
  # Value for the 'hellopage_setting' plugin
  hellopage:
    enable:                     true

# Settings to share the post on the social networks below.
share:
  facebook:                     true
  linkedin:                     true
  twitter:                      true
  googleplus:                   true



#  --- SESSION PRIVATE [Do not change anything in the private session unless you know what you are doing.]
# __________________________________________________________________________________________________________

# Automatic URL and BASEURL, not CHANGE!!!
# You should change in the file 'config/config.json', block "website =>" and "website => baseurl".
url: "http://localhost:3010"
baseurl: ""

# Settings Default
include:                        ['_pages','_blog']
markdown:                       kramdown
highlighter:                    pygments
permalink:                      /blog/:title/

# Collections
collections:
  projects:
    output: true

# Plugin jekyll-archive - https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category:                  archive_category
    tag:                       archive_tag
  permalinks:
    category:                  '/blog/category/:name/'
    tag:                       '/blog/tags/:name/'

# Keeping static files
keep_files:                    [images]

# Build local / Server
destination:                   _site

# Config SASS
sass:
  sass_dir:                    _sass
  style:                       compressed

# Config for Compress HTML
compress_html:
  clippings:                   all
  comments:                    all
  endings:                     []
  profile:                     false

# Exclude files (or folders) in compilation.
exclude:
  - url.json
  - node_modules
  - lib
  - backup
  - deploy
  - package-lock.json
  - src
  - Gemfile
  - Gemfile.lock
  - CHANGELOG
  - LICENSE.txt
  - package.json
  - gulpfile.babel.js
  - COPYING
  - "**/*.txt"
  - README.txt
  - init.sh
  - Rakefile

#  --- SESSION PRIVATE ---
