module HeaderPost
  def create_header_post(filename, title, date_hour, category)
    open(filename, 'w') do |file|
      file.puts("---")
      file.puts("layout: post")
      file.puts("date: #{date_hour}\n\n")
      file.puts("# Thumbnail for cardlist title.")
      file.puts("cardlist:")
      file.puts("  thumbnal: < add image 160x160 >.PNG|JPG")
      # file.puts("  color: \"#2A2A2A\"\n\n") # DEPRECATED
      file.puts("# Post banner setting (Image supported: 1920x500)")
      file.puts("banner:")
      file.puts("  image: < add image 1920x500 >.JPG")
      file.puts("  color: \"#FFF\"")
      file.puts("  shadow: \"#000\"\n\n")
      file.puts("# Post simple cover. E.g: #FFF")
      file.puts("cover:")
      file.puts("  color: \"#e9ff34\"")
      file.puts("title: #{title.gsub(/-/,' ')}")
      file.puts("subtitle: < add subtitle >")
      file.puts("category: #{category}\n\n")
      file.puts("# Add tags to make search easier.")
      file.puts("tags: ['tag1','tag2','tag3']\n\n")
      file.puts("published: false")
      file.puts("comments: false")
      file.puts("share: false\n\n")
      file.puts("# Momentary display text in postlist.")
      file.puts("excerpted: |
  \"Put here your excerpt\"\n\n")
      file.puts("# Message of the day.")
      file.puts("day_quote:")
      file.puts("  title: < add title >")
      file.puts("  content: |")
      file.puts("    \"< add message here >\"\n\n")
      file.puts("# Does not change and does not remove 'script_js' variable.")
      file.puts("script_js: [jekyll-search.min.js, post.js]\n\n")
      file.puts("# Events Google Analytics")
      file.puts("ga_event: false\n\n")
      file.puts("# Does not change and does not remove 'script_html' variable.")
      file.puts("script_html: [search.html]")
      file.puts("---")
      puts "✔ Created successfully!".green
    end
  end
end
